# Generated by Django 4.2.11 on 2026-04-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('cantidad_total', models.PositiveIntegerField(default=1, verbose_name='cantidad total')),
                ('cantidad_en_renta', models.PositiveIntegerField(default=0, verbose_name='en renta')),
                ('cantidad_en_mantenimiento', models.PositiveIntegerField(default=0, verbose_name='en mantenimiento')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipos/', verbose_name='imagen de referencia')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'ordering': ['nombre'],
            },
        ),
    ]
