# Generated by Django 4.2.11 on 2026-04-26 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alta_equipo', 'Alta de equipo'), ('edicion_equipo', 'Edición de equipo'), ('baja_equipo', 'Baja de equipo'), ('nueva_renta', 'Nueva renta'), ('cierre_renta', 'Cierre de renta')], max_length=30, verbose_name='tipo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('comentario', models.TextField(verbose_name='comentario')),
                ('datos_json', models.JSONField(blank=True, null=True, verbose_name='datos adicionales (JSON)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolución')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.equipo', verbose_name='equipo')),
                ('renta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentas.renta', verbose_name='renta')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='resuelto por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
