# Generated by Django 4.2.11 on 2026-04-26 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inventario', 'Inventario'), ('rentas', 'Rentas por periodo')], max_length=20, verbose_name='tipo de reporte')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de generación')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='periodo inicio')),
                ('periodo_fin', models.DateField(blank=True, null=True, verbose_name='periodo fin')),
                ('archivo_nombre', models.CharField(max_length=200, verbose_name='nombre de archivo')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='generado por')),
            ],
            options={
                'verbose_name': 'reporte generado',
                'verbose_name_plural': 'reportes generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
