# Generated by Django 4.2.11 on 2026-04-26 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='teléfono')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='dirección')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_vencimiento', models.DateField(verbose_name='fecha de vencimiento')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='fecha de devolución')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio (MXN)')),
                ('deposito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='depósito (MXN)')),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad que pagó el cliente al devolver el equipo.', max_digits=10, null=True, verbose_name='monto recibido al cierre (MXN)')),
                ('cambio_entregado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cambio entregado (MXN)')),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='', max_length=20, verbose_name='método de pago (depósito)')),
                ('metodo_pago_cierre', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='', max_length=20, verbose_name='método de pago (cierre)')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('vencida', 'Vencida')], default='activa', max_length=20, verbose_name='estado')),
                ('condicion_devolucion', models.CharField(blank=True, choices=[('bueno', 'Bueno — sin daños'), ('daños_menores', 'Daños menores'), ('inservible', 'Inservible / Pérdida total'), ('extraviado', 'Extraviado')], default='', max_length=20, verbose_name='condición al devolver')),
                ('cargo_daños', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cargo por daños (MXN)')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentas', to='rentas.cliente', verbose_name='cliente')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentas', to='inventario.equipo', verbose_name='equipo')),
                ('registrada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
            ],
            options={
                'verbose_name': 'renta',
                'verbose_name_plural': 'rentas',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='RentaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renta_items', to='inventario.equipo', verbose_name='equipo')),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentas.renta', verbose_name='renta')),
            ],
            options={
                'verbose_name': 'equipo de renta',
                'verbose_name_plural': 'equipos de renta',
            },
        ),
    ]
